name: HolySheetWebserver
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com
# author: RubbaBoy <adamyarris@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.5.0
  shelf: ^0.7.5
  shelf_router: ^0.7.2
  shelf_static: ^0.2.8
  grpc: ^2.1.3
  protobuf: any
  protoc_plugin: any
  fixnum: ^0.10.11

# protoc --dart_out=grpc:lib/generated -Iprotos protos/holysheet_service.proto

dev_dependencies:
  pedantic: ^1.8.0
