name: Build

on:
  push:
    branches:
      master

jobs:
  build-windows:
    name: Docker Build
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependensies
        run: pub get
      - name: Compile Dart
        run: dart2native bin/server.dart -k aot -o server.aot
      - name: Publish to Registry
          uses: HurricanKai/Publish-Docker-Github-Action@master
          if: contains(github.ref, 'refs/tags/v')
          with:
            name: rubbaboy/testback
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tagging: true
