name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    name: Docker Build
    runs-on: ubuntu-latest
    container:
      image:  google/dart:latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: pub get
      - name: Compile Dart
        run: dart2native bin/server.dart -k aot -o server.aot
      - name: Get branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: get_branch
      - name: Get commit hash
        shell: bash
        run: echo "##[set-output name=hash;]$(echo $(git rev-parse --short "$GITHUB_SHA") | cut -c1-8)"
        id: get_hash
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: rubbaboy/testback
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: "${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}"
      - name: Repository published
        run: echo "docker pull rubbaboy/testback:${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}"
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: bash
          REMOTE_DIR: /var/www/holysheet.net/public_html/bash
          ARGS: --delete
      - name: Create docker shield
        run: |-
          mkdir -p shields/holysheetwebserver && echo "{ \"schemaVersion\": 1, \"label\": \"docker\", \"message\": \"rubbaboy/testback:${{ steps.get_branch.outputs.branch }}-${{ steps.get_hash.outputs.hash }}\", \"color\": \"#0576b7\" }" >> "shields/holysheetwebserver/${{ steps.get_branch.outputs.branch }}.json"
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: shields
          REMOTE_DIR: /var/www/holysheet.net/public_html/shields
